---
title: "Free Online Resources for R"
subtitle: "Advance your analytical skills for free with online R resources"
title-block-banner: "white"
title-block-banner-color: "black"
format: 
  html:
    toc: true
    toc-title: Contents
    embed-resources: true
    fontcolor: black
author: Madison Merzke, MAS, BPH
date: last-modified
editor: visual
css: styles.css
---

## How to Use This List

This list of free, online resources for R is organized, first by medium (e-book/website, video, event/community space, etc), and then by subject. **It was compiled by data scientists working in the public health and social science spheres for professionals seeking to grow their R skills.**

Many thanks to all of the authors, organizers, and contributors in the R world, who have taught us all so much! If you have a resource you'd like to propose we add, please [message me on LinkedIn](https://www.linkedin.com/in/madisonmerzke/).

## Free Online E-Books & Websites

### Introductory

[R for Data Science](https://r4ds.hadley.nz/) - the bible; if you're new to R and the `tidyverse`, start here!

[The Epidemiologist R Handbook](https://epirhandbook.com/en/) - great introductory resource and reference tailored for applied epidemiology and public health

[R Cookbook by Long & Teetor (2019)](https://rc2e.com/) - Great resource for foundational tasks in R, organized by problem / solution / discussion of specific issues

[Posit cheatsheets](https://posit.co/resources/cheatsheets/) - Cheatsheets for basic commands and helpful tricks across a variety of packages in the tidyverse and working in Rmarkdown

[Data Science Illustrations by Horst](https://allisonhorst.com/data-science-art) - Data science and statistics artwork that visualizes R commands and includes syntax

::: callout-important
To save yourself time, get comfortable referencing R package documentation! Most common packages have fantastic, easily accessible online documentation that provide details on how to use them. For example, I use [`stringr` functions with regular expressions](https://stringr.tidyverse.org/articles/regular-expressions.html) all the time and reference that page constantly. I can almost guarantee you that at least half of your R journey will be learning how to answer your own questions using the internet!
:::

### Statistical Techniques with R

[Tidy Modeling with R](https://www.tmwr.org/) - goes deeper into modeling with `tidymodels` packages

[Handbook of Regression Modeling in People Analytics](https://peopleanalytics-regression-book.org/) - "a starting point for a practical learning of regression methods," focused on people analytics

[Meta-Analysis Learning Information Center](https://www.meta-analysis-learning-information-center.com/getting-started-with-meta-analysis) - introduction to using R for meta-analysis

[Biostatistics for Biomedical Research](https://hbiostat.org/bbr/) - "aimed at exposing biomedical researchers to modern biostatistical methods and statistical graphics, highlighting those methods that make fewer assumptions, including nonparametric statistics and robust statistical measures"

[Exploring Complex Survey Data Analysis Using R](https://tidy-survey-r.github.io/tidy-survey-book/) - "*A Tidy Introduction with {srvyr} and {survey}*"

[The Missing Book by Tierney and Horst (2022)](https://tmb.njtierney.com/) - How to identify, wrangle, and work with missing data in R

[Exploratory Data Analysis with R by Roger Peng (2020)](https://bookdown.org/rdpeng/exdata/) - Focus on data wrangling and analysis

::: callout-tip
If you're working with large data sets that take time to read in, trying using [`vroom()`](https://vroom.r-lib.org/) to read them in much faster!
:::

### Working with Qualitative Data

[Text Mining with R: A Tidy Approach](https://www.tidytextmining.com/) - the basics of NLP with R, a great place to start

[quanteda: Quantitative Analysis of Textual Data](https://quanteda.io/articles/quickstart.html)

### Data Visualization

Many of the other resources listed include sections on data visualization. However, the below may provide some additional inspiration:

[The R Graph Gallery – Help and inspiration for R charts](https://r-graph-gallery.com/) (Examples of plots created in R with reproducible code. Great place to click around for inspiration!)

[Tidy Plots for Scientific Papers • tidyplots](https://jbengler.github.io/tidyplots/)

[Shiny Tutorial](https://shinylive.io/r/examples/#hello-shiny) - Shiny is a package that builds interactive web apps (think dashboard, etc.). Resource that shows the possibilities

[shinylive](https://posit-dev.github.io/r-shinylive/)- create and deploy Shiny apps without a server!

[From Data to Viz](https://www.data-to-viz.com/) - What kind of data visualizations can you make with the types of data you have? Provides R code for each visualization

[Top 50 ggplot2 Visualizations (with Full R Code)](https://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)

ggplot2 recorded webinars by Thomas Lin Pederson:

-   [Part one](https://www.youtube.com/watch?v=h29g21z0a68)

-   [Part two](https://www.youtube.com/watch?v=0m4yywqNPVY)

### Sharing Your Work

::: callout-tip
Leverage Quarto and GitHub to create a free, online portfolio of work you can share with your network and use in the job search process!
:::

[Happy Git and GitHub for the useR](https://happygitwithr.com/) - learn to use Git for version control and to share your code and projects

[R Workflow for Reproducible Data Analysis and Reporting](https://hbiostat.org/rflow/) - collection of associated best practices

[Tidyverse style guide](https://style.tidyverse.org/) - make your code more readable! You can automate a lot of this with [`styler`](https://styler.r-lib.org/), which can now reformat your code in RStudio upon save (within updated version of RStudio)

[Quarto](https://quarto.org/docs/guide/) - learn about all of the creative, cool outputs you can create with R and Quarto, right in RStudio!

[Quarto Live](https://r-wasm.github.io/quarto-live/) - add interactive code to your outputs!

## Free Online Videos

[Posit::conf(2024) talks](https://www.youtube.com/playlist?list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn) - varying topics, but inspiring and super informative

## Free Online Events & Community Spaces

::: callout-tip
One of the best ways to keep growing in your R skills is to engage with other useRs! There are many conferences and events, both virtually and free or in-person, depending on your preferences and budget! **You can also add this into your daily routine by connecting with or following others useRs on LinkedIn, BlueSky, or other social media of your choice! I have learned so much via examples other brilliant useRs have shared.**
:::

[TidyTuesday](https://github.com/rfordatascience/tidytuesday) - weekly exercises with associated Slack; post your results with #TidyTuesday!

[Posit's Data Science Hangout](https://posit.co/data-science-hangout/) - weekly call, Thursday at noon EST

[Workflows with Posit Team](https://www.youtube.com/playlist?list=PL9HYL-VRX0oRsUB5AgNMQuKuHPpNDLBVt) - More advanced topics for R (e.g., ShinyApps, using Python in R)

## Free Online Courses

Many online courses are free or low-cost, such as Coursera's [Statistical Analysis with R for Public Health Specialization](https://www.coursera.org/specializations/statistical-analysis-r-public-health). Also, we suggest you consider what free resources you might be able to access through your connections or community. For example, veterans and military spouses can often get a free year-long account on Coursera or Udemy through their programs.

[Free R programming online courses](https://www.edx.org/learn/r-programming)

[Ggplot2 course](https://www.edx.org/learn/data-visualization/harvard-university-data-science-visualization) with Harvard

## Other Free Online Tools

[learnr](https://rstudio.github.io/learnr/) - R package that creates interactive tutorials to learn R. "Examples" tab includes some useful tutorials

[swirl](https://swirlstats.com/) - R package that includes interactive learning courses
